# src/Acme/StoreBundle/Resources/config/doctrine/Product.orm.yml
Acme\TaskBundle\Entity\Sub3:
    type: entity
    table: sub3
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100
    task_id:
              type: integer(FK)