# src/Acme/StoreBundle/Resources/config/doctrine/Product.orm.yml
Acme\TaskBundle\Entity\Sub6:
    type: entity
    table: sub6
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100
    relations:
    taskid:
      class: Task
      local: task_id
      foreign: id
      foreignAlias: Task
      foreignType: one
      type: one 
            
   