parameters:
#    acme_plans.example.class: Acme\PlansBundle\Example

services:
#    acme_plans.example:
#        class: %acme_plans.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
